### ISSUE TITLE
Fatal error: expat.h: No such file or directory

### ISSUE THREAD

**Issue by asavin** [scottcorgan/bucket-list#2]
Getting following error when installing bucket-list npm package:

``` sh
> node-expat@1.6.1 install /vagrant/node_modules/bucket-list/node_modules/xml-object-stream/node_modules/node-expat
> node-gyp rebuild

make: Entering directory `/vagrant/node_modules/bucket-list/node_modules/xml-object-stream/node_modules/node-expat/build'
make: Warning: File `node_expat.target.mk' has modification time 9.8e+02 s in the future
  CXX(target) Release/obj.target/node_expat/node-expat.o
../node-expat.cc:6:19: fatal error: expat.h: No such file or directory
 #include <expat.h>
                   ^
compilation terminated.
make: *** [Release/obj.target/node_expat/node-expat.o] Error 1
make: Leaving directory `/vagrant/node_modules/bucket-list/node_modules/xml-object-stream/node_modules/node-expat/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.11.0-15-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /vagrant/node_modules/bucket-list/node_modules/xml-object-stream/node_modules/node-expat
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm http 304 http://registry.npmjs.org/mime-magic
npm http 304 http://registry.npmjs.org/xml2js
npm ERR! node-expat@1.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@1.6.1 install script.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.11.0-15-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "bucket-list"
npm ERR! cwd /vagrant
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm http 304 http://registry.npmjs.org/libxml-to-js
npm http GET http://registry.npmjs.org/sax
npm http GET http://registry.npmjs.org/xmlbuilder
npm http GET http://registry.npmjs.org/libxmljs
npm http 304 http://registry.npmjs.org/xmlbuilder
npm http 304 http://registry.npmjs.org/sax
npm http 304 http://registry.npmjs.org/libxmljs

```

**Comment by DiegoRBaquero** [comment]
Same here. Thank you!

**Comment by s8sg** [comment]
Thanks.
`yum install expat-devel`  in Centos

**Comment by the-tuxedo-cat** [comment]
Yeah that worked for this specific issue..

**Comment by keyhole425** [comment]
Had this problem on an issue relating to installing Perl's XML::Simple or XML::Parser libraries on a Debian 9 Stretch image.  CPAN was complaining about XML::Simple install not having expat.h.

This was resolved by using:
`sudo apt-get install libexpat1-dev`

Strangely enough, the non-dev option didn't work:
`sudo apt-get install libexpat1`

Posting for others who might have the issue, and also as a thanks to @elsbree

**Comment by wcomhelp** [comment]
Ran into this in 2019 on CentOS7. You cannot just install expat, you have to yum install expat-devel to get the development version needed to compile git.
